// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Sampling() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><script src=\"../path/to/flowbite/dist/datepicker.js\"></script><div class=\"flex justify-center\"><h2 class=\"text-2xl font-bold mb-4 font-body\">Selecione o Intervalo de Datas</h2></div><form id=\"dateRangeForm\" class=\"space-y-4\"><div><label for=\"startDate\" class=\"block font-medium font-body\">Data de Início:</label> <input type=\"date\" id=\"startDate\" name=\"startDate\" min=\"2023-10-16\" value=\"2023-10-16\" class=\"border rounded-md p-2 w-full text-white bg-black bg-opacity-80\"> <label for=\"endDate\" class=\"block font-body\">Data de Término:</label> <input type=\"date\" id=\"endDate\" name=\"endDate\" min=\"2023-10-16\" value=\"2023-10-16\" class=\"border rounded-md p-2 w-full text-white bg-black bg-opacity-80\"> <button type=\"submit\" class=\"my-button\">Aplicar Filtro</button></div></form></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
